AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%I": "()"
    "%q": "()"
    "%Q": "()"
    "%r": "()"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
